# -*- coding: utf-8 -*-
"""LinearRegression_NN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GPLBUi4hPtLV9pu3W_1Vkg0-_A8ktKdK
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn import datasets
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)

diabetes_X=diabetes_X[:, np.newaxis, 2]

diabetes_X_train, diabetes_X_test, diabetes_y_train, diabetes_y_test = train_test_split(diabetes_X, diabetes_y, test_size=0.2, random_state=1)

reg = LinearRegression()
reg.fit(diabetes_X_train, diabetes_y_train)

print(reg.intercept_)
print(reg.coef_)

diabetes_y_pred = reg.predict(diabetes_X_test)
df = pd.DataFrame({'Actual': diabetes_y_test, 'Predicted': diabetes_y_pred})
df

plt.scatter(diabetes_X_test[:,0], diabetes_y_test, color="black")
plt.plot(diabetes_X_test[:,0], diabetes_y_pred, color="red", linewidth=3)
plt.xticks(())
plt.yticks(())
plt.show()

"""# New Section"""